### PR TITLE
Voting feature

### PR DESCRIPTION
**Pull request by kesar**
# Voting feature
A way for voting inside of our UI

## How should this be tested?
yarn
yarn start
## Notes or observations
wip
## Linked issues
closes https://github.com/EveripediaNetwork/iq-bridge-ui/issues/40

### CODE REVIEW

**Comment by JustinCast** [comment]
@kesar feel free to make me observations (if any), regarding last changes

**Comment by kesar** [comment]
> @kesar feel free to make me observations (if any), regarding last changes

nice stuff! love the select!

a) Select a proposal should have the latest one by default
b) when you select one data should flow inside of the main card. Probably we can add a div with a scroll to allow scrolling that content
c) change CSS for h2 to be around 1.2em rn its too big inside of that div
d) I noticed that there will be a lot of shitty proposals, so we will need a filter in the JS (not UI, just in the JS) of a list of valid proposers that we will show in the UI

**Comment by JustinCast** [comment]
> > @kesar feel free to make me observations (if any), regarding last changes
> 
> nice stuff! love the select!
> 
> a) Select a proposal should have the latest one by default
> b) when you select one data should flow inside of the main card. Probably we can add a div with a scroll to allow scrolling that content
> c) change CSS for h2 to be around 1.2em rn its too big inside of that div
> d) I noticed that there will be a lot of shitty proposals, so we will need a filter in the JS (not UI, just in the JS) of a list of valid proposers that we will show in the UI

Ok, noted. Thanks!

**Comment by kesar** [comment]
Captura de pantalla 2021-06-15 a las 11 12 17

Captura de pantalla 2021-06-15 a las 11 12 47

- To avoid UI increasing in size, you can set a min-height with a spinner while loading the chart
- proposal selector is not obvious that clicking there you will get the list / data. Probably adding an arrow in the end might make it more understandable. Also it could be a bit longer

Captura de pantalla 2021-06-15 a las 11 17 28


---

- Remove open in snapshot link and have two buttons Select for Voting // Go to Proposals . Primary most likely should be select for voting.
- Change text-info to text-primary for title
- Instead of start & End I would show just Ending in.... X or Ended at date (depending of the state) or Starting in ... X

Captura de pantalla 2021-06-15 a las 11 19 12

Captura de pantalla 2021-06-15 a las 11 18 31



Its looking very good! just those small tweaks 👍🏻

**Comment by JustinCast** [comment]
@kesar thank you for the suggestions I'll check them out

**Comment by JustinCast** [comment]
@kesar your suggestions were implemented.

-- 
Need some help with the signing process, 'cause we are getting an error when trying to broadcast the vote: 

image
_this is what we get when the wallet ask us to sign_

image
_what we get when the accept the signing request_

I'm trying to use a snapshot client instance to broadcast the vote, just raw values for now:
https://github.com/EveripediaNetwork/iq-bridge-ui/blob/8e1e52426256bc366f50714d4e8684720aa54248/src/helpers/snapshotClient.js

Pd: it seems that the error is somehow related with apollo graphql (used in the snapshot library)
https://stackoverflow.com/questions/54080189/apollo-server-graphql-must-provide-query-string

**Comment by kesar** [comment]
I would suggest to try first to implement something like this, so we don't need to add a full library for just a vote call: 

https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/src/plugins/Snapshot/apis/index.ts

**Comment by kesar** [comment]
Pie chart should be based in voting power not in number of people 👍🏻

**Comment by JustinCast** [comment]
@kesar I think this PR is ready to be reviewed

**Review by JustinCast — APPROVED** [review]
LGTM

**Comment by kesar** [comment]
We can merge this but I think we need to handle multi selection proposals. We can create a different PR for that, so that way its not stoping to push this to prod.

When you create a proposal you can choose if users can select one option or multiple. We might need to tweak it to support that as well.

I guess we also need the translations for cz & ko that can be added into that PR

**Pull request merged**
