### PR TITLE
Refactor/lock stats rewards

### LINKED ISSUE #123: HiIQ Rewards refactor
- [x] Remove feeDistributor contract interaction
- [x] Reimplement feeDistributor contract interaction
- [x] Calculate APR based on Rich's calculations
- [x] Implement a simple future rewards calculator
- [x] Add i18n key entries

### PR DESCRIPTION
**Pull request by JustinCast**
# Refactor lock stats and reimplement rewards interaction
_HiiQ rewards interaction has been reimplemented due to the removal of the feedistributor interaction, to allow users to claim. Also, useful stats have been included_
## How should this be tested?
1. yarn start
## Notes or observations
_we've got no observations_
## Linked issues
closes #123

### CODE REVIEW

**Comment by kesar** [comment]
Next Distribution -> there is no next distribution on the new contract
reward calculation does not work -> if does not work, dont show it in the UI

**Comment by JustinCast** [comment]
> Next Distribution -> there is no next distribution on the new contract
> reward calculation does not work -> if does not work, dont show it in the UI

Sure @kesar. Could extend why is not working for you?. Since the rewards calculator is working for me locally

**Comment by kesar** [comment]
pls fix conflicts

**Comment by kesar** [comment]
Captura de pantalla 2021-09-16 a las 11 30 43

where is the checkpoint button?

**Comment by JustinCast** [comment]
> Captura de pantalla 2021-09-16 a las 11 30 43
> 
> where is the checkpoint button?

The checkpoint method is called when:
- Create lock
- Increase amount
- Increase unlock time
https://github.com/EveripediaNetwork/iq-bridge-ui/blob/289878d7b6c3b8fd148acf117ef00cfe8f12d601/src/features/Lock/lock.js#L151

**Comment by kesar** [comment]
> > Captura de pantalla 2021-09-16 a las 11 30 43
> > where is the checkpoint button?
> 
> The checkpoint method is called when:
> 
> * Create lock
> * Increase amount
> * Increase unlock time
>   https://github.com/EveripediaNetwork/iq-bridge-ui/blob/289878d7b6c3b8fd148acf117ef00cfe8f12d601/src/features/Lock/lock.js#L151

what if user already create lock? 

we discussed that earlier, the button was there

**Comment by kesar** [comment]
btw i guess we can fix all those stuff in the other branch and close this one right?

**Comment by JustinCast** [comment]
> btw i guess we can fix all those stuff in the other branch and close this one right?

Yep. I gonna close the branch now.

**Pull request closed without merging**
