### PR TITLE
fix: avoid input special chars in the swap input

### LINKED ISSUE #28: click in balance to input improvements
image

image

a) big numbers / numeric input breaks layout
b) no need to have an arrow or any icon, all the uniswap style AMM have this feature so just let users to click in the balance (already pushed small change to remove that)
c) there is a comma there ( I guess based in my locals), that's gonna break most likely bridges & locking txs

image

### PR DESCRIPTION
**Pull request by JustinCast**
# Bug fixes
_Some bug fixes_
## How should this be tested?
1. `yarn start`
## Notes or observations
_Make sure you setup env vars correctly_
## Linked issues
closes #28

### CODE REVIEW

**Comment by kesar** [comment]
this wont work because you are validating each time that you input a number... For example you can't type "1.5" because when you add the "." it returns NaN

validation needs to be done in a different way, on focus out, or with a less strict validation while typing


Captura de pantalla 2021-06-02 a las 19 07 32

**Review by kesar — CHANGES_REQUESTED** [review]
https://github.com/EveripediaNetwork/iq-bridge-ui/pull/36#issuecomment-853227610

**Comment by kesar** [comment]
it looks good, i found a minor issue:

- type something wrong and then click in the balance to fill with right data

we can merge it once that's solved 👍🏻

**Comment by JustinCast** [comment]
> it looks good, i found a minor issue:
> 
> * type something wrong and then click in the balance to fill with right data
> 
> image
> 
> we can merge it once that's solved 👍🏻

Fixed!!

**Review by kesar — APPROVED** [review]

**Comment by kesar** [comment]
cool! feel free to merge!

btw if you could just branch here, it would make vercel to work automatically, if you do fork from your account i think it does not work fine ( I have to manually accept it )

**Comment by JustinCast** [comment]
> cool! feel free to merge!
> 
> btw if you could just branch here, it would make vercel to work automatically, if you do fork from your account i think it does not work fine ( I have to manually accept it )
> 
> as you are member of the repo i dont think its needed that you fork it to your account 👍🏻
> 
> great work with the isInvalid, i didnt know about that, and I just implemented it for the ethereum / eos addresses validation on the branch I am working :)

Ok ok, got it. So I gonna use this repo as my main remote instead of my fork. And thanks, we get better solutions when we push a little bit harder

**Pull request merged**
