### PR TITLE
Feat/lock stats

### LINKED ISSUE #120: Extend stats
## Stats & data representation:
- [x] Amount of HIIQ for periods of time (using chartjs)
- [ ] unique address count of all stakers.

### Notes
image

### PR DESCRIPTION
**Pull request by JustinCast**
# Stats charts
_Useful charts for the lock section: Lock Breakdown chart and top 10 holders chart_
## How should this be tested?
1. `yarn start`
## Notes or observations
_Depends on https://github.com/EveripediaNetwork/iq-bridge-ui/pull/126_
## Linked issues
closes #120

### CODE REVIEW

**Comment by kesar** [comment]
Captura de pantalla 2021-09-16 a las 11 35 05

getting this after few seconds on the lock page

**Comment by kesar** [comment]
Captura de pantalla 2021-09-16 a las 16 05 30

we dont need to show precision 18, with 4 should be fine

**Comment by JustinCast** [comment]
@kesar lmk any feedback

**Comment by kesar** [comment]
> @kesar lmk any feedback

ok, but make sure you also test all the changes and scenarios on goerli

**Pull request merged**
